-- ============================================================
-- CHAE LAUNDRY - SUPABASE SCHEMA
-- Jalankan SQL ini di Supabase SQL Editor
-- ============================================================

-- 1. TABEL: services (Daftar Layanan Laundry)
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL,
    price_per_kg NUMERIC NOT NULL,
    estimate_hours INT NOT NULL,
    is_available BOOLEAN DEFAULT true,
    icon TEXT DEFAULT '🧺',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABEL: orders (Data Transaksi Laundry)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES public.services(id) ON DELETE RESTRICT,
    weight_kg NUMERIC NOT NULL,
    total_price NUMERIC NOT NULL,
    status TEXT CHECK (status IN ('pending', 'proses', 'selesai', 'terkirim')) DEFAULT 'pending',
    pickup_address TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. SEED DATA: Layanan Laundry
INSERT INTO public.services (service_name, price_per_kg, estimate_hours, icon) VALUES
('Wash & Fold', 12000, 24, '🧺'),
('Dry Cleaning', 75000, 48, '👔'),
('Express Wash', 20000, 6, '⚡'),
('Household Items', 40000, 72, '🏠'),
('Setrika Saja', 8000, 24, '👕'),
('Cuci Komplit', 15000, 24, '🧼');

-- 4. RLS POLICIES (Row Level Security)
-- Aktifkan RLS
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Policy: services bisa dibaca semua user (termasuk guest via anon key)
CREATE POLICY "Services public read" ON public.services
    FOR SELECT USING (true);

-- Policy: orders - user hanya bisa melihat order milik sendiri
CREATE POLICY "Orders user read own" ON public.orders
    FOR SELECT USING (auth.uid() = user_id OR (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin');

-- Policy: orders - user bisa insert order milik sendiri
CREATE POLICY "Orders user insert own" ON public.orders
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 5. ENABLE REAL TIME (opsional)
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
